name: bodyshield
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - pillow
  - pyarrow
  - pyyaml
  - pytest
  - pip:
      - pypdf
      - tabulate
